name: hedieaty_app
description: "Hedieaty is a gift list management app designed to streamline the process of creating, 
  managing, and sharing wish lists for special occasions such as birthdays, weddings, 
  engagements, graduations, and holidays. The app features a user-friendly interface that 
  allows users to easily add gifts to their lists, either manually or through an integrated barcode 
  scanner. With Hedieaty, users can manage their lists flexibly, including adding, deleting, and 
  modifying items at any time—except for items that have been pledged. The app also enables 
  users to publish their lists to the cloud, allowing friends and family to view and pledge to 
  purchase gifts, enhancing the joy of gift-giving. The app should be designed using Flutter and 
  published on Appstore, Google Play Store, and/or Amazon App Store."
  
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

assets:
  assets/

flutter:
  uses-material-design: true
