name: hedieaty_app
description: |
  Hedieaty is a gift list management app designed to streamline the process of creating, 
  managing, and sharing wish lists for special occasions. The app features a user-friendly 
  interface that allows users to add gifts manually or through an integrated barcode scanner. 

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  google_fonts: ^6.2.1
  intl: ^0.17.0
  firebase_messaging: ^15.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  integration_test:
      sdk: flutter

assets:
  - assets/

flutter:
  uses-material-design: true
