// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8zq3xb7TGTPXK1XugXpVygy7Mlu31IYY',
    appId: '1:205361895070:web:afdc8449e7cfe1260a0d8f',
    messagingSenderId: '205361895070',
    projectId: 'mp-hedieaty-app',
    authDomain: 'mp-hedieaty-app.firebaseapp.com',
    storageBucket: 'mp-hedieaty-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bGSunpOJnUiCHeFOItVcUp-Zo2dV2uM',
    appId: '1:205361895070:android:7582e97cefe75a510a0d8f',
    messagingSenderId: '205361895070',
    projectId: 'mp-hedieaty-app',
    storageBucket: 'mp-hedieaty-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEcZu2-WVBhiWLal0OBjVJwFPTlSPiHiw',
    appId: '1:205361895070:ios:cc33e38b649028040a0d8f',
    messagingSenderId: '205361895070',
    projectId: 'mp-hedieaty-app',
    storageBucket: 'mp-hedieaty-app.firebasestorage.app',
    iosBundleId: 'com.example.hedieatyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEcZu2-WVBhiWLal0OBjVJwFPTlSPiHiw',
    appId: '1:205361895070:ios:cc33e38b649028040a0d8f',
    messagingSenderId: '205361895070',
    projectId: 'mp-hedieaty-app',
    storageBucket: 'mp-hedieaty-app.firebasestorage.app',
    iosBundleId: 'com.example.hedieatyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8zq3xb7TGTPXK1XugXpVygy7Mlu31IYY',
    appId: '1:205361895070:web:c4b0935dd56662b00a0d8f',
    messagingSenderId: '205361895070',
    projectId: 'mp-hedieaty-app',
    authDomain: 'mp-hedieaty-app.firebaseapp.com',
    storageBucket: 'mp-hedieaty-app.firebasestorage.app',
  );
}
